Extensie Join condition
CrossBreezeNL/PowerDesigner-MDDE-Extension pull request #31
Opened 2024-09-17 15:05 UTC by RichaneCrossbreeze

De extensie van de join condition teller op de source object

2024-09-17 21:00 UTC, harmen-xb requested changes
Ha Richane,

Ik heb je wijzigingen doorgenomen. Over geheel is het goed, alleen als ik de stukjes code bekijk kan het wat efficiënter door niet zelf te tellen en wat controles weg te laten op situaties die niet voor kunnen komen.

2024-09-17 21:00 UTC, harmen-xb commented on decomposed/extensions/MDDE_LDM/Profile/ExtendedSubObject/Stereotypes/mdde_SourceObject/Extended_Attributes/mdde_NumberOfJoinConditions.xml
> +            joinCount = joinCount + 1
@RichaneCrossbreeze collections in PowerDesigner hebben een Count property. Dan hoef je zelf niet te tellen. Dus als de collection niet nothing is kun je meteen de Count property pakken i.p.v. zelf tellen.

Je kunt dit zien in de PowerDesigner metamodel help bij ObjectBag volgens mij.

2024-09-17 21:00 UTC, harmen-xb commented on decomposed/extensions/MDDE_LDM/Profile/ExtendedSubObject/Stereotypes/mdde_SourceObject/Extended_Attributes/mdde_NumberOfJoinConditions.xml
> +   If Not obj Is Nothing Then
Volgens mij kan obj nooit Nothing zijn hier omdat de methode op het object afgaat. Deze if is dus volgens mij niet nodig.

2024-09-17 21:00 UTC, harmen-xb commented on decomposed/extensions/MDDE_LDM/Profile/ExtendedSubObject/Stereotypes/mdde_SourceObject/Extended_Compositions/mdde_JoinConditions.xml
> +<a:DestinationStereotype>mdde_EntityExampleData</a:DestinationStereotype>
Heb je dit bewust gewijzigd?

2024-09-17 21:00 UTC, harmen-xb commented on decomposed/extensions/MDDE_LDM/Profile/ExtendedSubObject/Stereotypes/mdde_SourceObject/Extended_Compositions/mdde_JoinConditions.xml
> -<a:DefaultColumnFilter>&quot;_MDDE_LDM.mdde_ChildAttributeSelector.{4448B089-2B01-4D49-83CA-70CEDD1812F4}&quot; 80 &quot;_MDDE_LDM.mdde_JoinOperator.{2AA569D6-094E-4EA8-BBFF-713196E44D4E}&quot; 80 &q
Hier lijk je de column filter hebben aangepast. Is dit bewust?

2024-09-18 07:11 UTC, RichaneCrossbreeze commented on decomposed/extensions/MDDE_LDM/Profile/ExtendedSubObject/Stereotypes/mdde_SourceObject/Extended_Compositions/mdde_JoinConditions.xml
> +<a:DestinationStereotype>mdde_EntityExampleData</a:DestinationStereotype>
nee niet bewust gewijzigd, even kijken of ik dit kan terugveranderen

2024-09-18 07:12 UTC, RichaneCrossbreeze commented on decomposed/extensions/MDDE_LDM/Profile/ExtendedSubObject/Stereotypes/mdde_SourceObject/Extended_Compositions/mdde_JoinConditions.xml
> -<a:DefaultColumnFilter>&quot;_MDDE_LDM.mdde_ChildAttributeSelector.{4448B089-2B01-4D49-83CA-70CEDD1812F4}&quot; 80 &quot;_MDDE_LDM.mdde_JoinOperator.{2AA569D6-094E-4EA8-BBFF-713196E44D4E}&quot; 80 &q
Dit heb ik ook niet bewust gedaan, even kijken of ik dit kan oplossen

2024-09-19 08:35 UTC, harmen-xb commented on decomposed/extensions/MDDE_LDM/Profile/ExtendedSubObject/Stereotypes/mdde_SourceObject/Extended_Attributes/mdde_NumberOfJoinConditions.xml
>     Dim joinConditions
Dim colJoinConditions : Set colJoinConditions  = obj.GetExtendedCollection(&quot;mdde_JoinConditions&quot;, False)

If colJoinConditions  Is Not Nothing Then
%Get% = colJoinConditions.Count
Else
%Get% = 0
EndIf

2024-09-19 08:43 UTC, harmen-xb commented on decomposed/extensions/MDDE_LDM/Profile/ExtendedSubObject/Stereotypes/mdde_SourceObject/Extended_Compositions/mdde_JoinConditions.xml
> +<a:DestinationStereotype>mdde_JoinConditions</a:DestinationStereotype>
This should be mdde_JoinCondition (not plural)

2024-09-19 08:43 UTC, harmen-xb requested changes
Some changes are required.

2024-09-19 13:44 UTC, closed without merging